language: python
python:
  - '2.7'
  - '3.5'
  - '3.6'
jobs:
  include:
    - python: '2.6'
      dist: trusty
    - python: '3.7'
      dist: xenial
install: pip install -r test-requirements.txt
script: python setup.py test
